[languages.py]
compile = "python {path}"
execute = "python {path}"
bundle = "false"
list_attributes = "sed 's/^# verify-helper: // ; t ; d' {path}"
list_dependencies = "sed 's/^# @import \\(.*\\)$/\\1/ ; t ; d' {path}"
